// Game scene mock-data to use for creating the UI but to be eventually replaced by data fetched from backend API
const games = [
    {
        id: 0,
        name: "A Dream Come True",
        image: "https://i.imgur.com/pk88M60.jpeg",
        characters: [
            {
                id: "waldo",
                name: "Waldo",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wenda",
                name: "Wenda",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wizard",
                name: "Wizard",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "odlaw",
                name: "Odlaw",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
        ],
    },

    {
        id: 1,
        name: "A Dream Come True",
        image: "https://i.imgur.com/pk88M60.jpeg",
        characters: [
            {
                id: "waldo",
                name: "Waldo",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wenda",
                name: "Wenda",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wizard",
                name: "Wizard",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "odlaw",
                name: "Odlaw",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
        ],
    },

    {
        id: 2,
        name: "A Dream Come True",
        image: "https://i.imgur.com/pk88M60.jpeg",
        characters: [
            {
                id: "waldo",
                name: "Waldo",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wenda",
                name: "Wenda",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wizard",
                name: "Wizard",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "odlaw",
                name: "Odlaw",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
        ],
    },

    {
        id: 3,
        name: "A Dream Come True",
        image: "https://i.imgur.com/pk88M60.jpeg",
        characters: [
            {
                id: "waldo",
                name: "Waldo",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wenda",
                name: "Wenda",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wizard",
                name: "Wizard",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "odlaw",
                name: "Odlaw",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
        ],
    },

    {
        id: 4,
        name: "A Dream Come True",
        image: "https://i.imgur.com/pk88M60.jpeg",
        characters: [
            {
                id: "waldo",
                name: "Waldo",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wenda",
                name: "Wenda",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wizard",
                name: "Wizard",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "odlaw",
                name: "Odlaw",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
        ],
    },

    {
        id: 5,
        name: "A Dream Come True",
        image: "https://i.imgur.com/pk88M60.jpeg",
        characters: [
            {
                id: "waldo",
                name: "Waldo",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wenda",
                name: "Wenda",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "wizard",
                name: "Wizard",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
            {
                id: "odlaw",
                name: "Odlaw",
                xMin: 2274,
                xMax: 2313,
                yMin: 592,
                yMax: 654,
            },
        ],
    },
];

export default games;